version: '3'
services:
  nodejs-boilerplate:
    image: dtr.${DOCKER_DOMAIN}/${DTR_ORG_NAME}/${DTR_REPO_NAME}:${BUILD_SOURCEVERSION}
    ports:
      - "4000"
    environment:
      - ENC_SALT=${ENC_SALT}
    labels:
      com.docker.ucp.mesh.http: "true"
    networks:
      default:
      hrm:
#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://$GRAYLOG_HOST:12201"
#        tag: "postclosing-userrole-${NAME_ENV}"
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        com.docker.ucp.mesh.http: "external_route=http://$LAUNCH_URL_HOST,internal_port=4000"
        com.docker.ucp.access.label: ${DDC_COLLECTION}
      mode: global
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0'
        reservations:
          cpus: '0'
networks:
  default:
  hrm:
    external:
      name: ${DDC_NETWORK}